Added dependabot config
palomachain/pigeon pull request #92
Opened 2023-03-02 07:58 UTC by mszuyev

# Related Github tickets

- https://github.com/VolumeFi/paloma/issues/6

# Background

We want to use separate non-master branch for Dependabot PRs

# Testing completed

- [ ] nothing has changed in the code, so no tests

2023-03-02 14:14 UTC, measure-fi approved these changes
lgtm % comments

2023-03-02 14:14 UTC, measure-fi commented on .gitignore
> +.idea
Can you set your editor (which I guess is goland?) to append a newline at the end of the file when you save. Also preferable sort the whole `.gitignore`.

2023-03-02 14:33 UTC, taariq commented
@mszuyev as per our note. We'll keep dependabot updates on pigeon over on Paloma on the master branch there. We'll merge and sync our pigeon here. No need for this PR. closing.

2023-03-02 20:15 UTC, taariq requested changes
Please UPDATE this PR for dependabot to update on pigeon master. We'll SYNC volume/pigeon master after the update.

2023-03-04 07:48 UTC, mszuyev commented
Added Dependabot config in a different PR, closing this one

2023-03-04 07:48 UTC, closed without merging